#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_troubleticket:
    prefix: /troubleticket
    resource: './routes/troubleticket/routes.yaml'
