App\Entity\Troubleticket\ProvidersCache:
    type: entity
    table: troubleticket.providers_cache
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cnpj:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        razaoSocial:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: razao_social
        nomeFantasia:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: nome_fantasia
    lifecycleCallbacks: {  }
